steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/alpine-website:latest', '-t', 'gcr.io/$PROJECT_ID/alpine-website:$TAG_NAME', '-f', 'Dockerfile', '..']
  dir: 'docker'

images: ['gcr.io/$PROJECT_ID/alpine-website:latest', 'gcr.io/$PROJECT_ID/alpine-website:$TAG_NAME']
