steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ownersearch-176101/website-server:latest', '-t', 'gcr.io/ownersearch-176101/website-server:$TAG_NAME', '-f', 'Dockerfile', '..']
  dir: 'docker'

images: ['gcr.io/ownersearch-176101/website-server:latest', 'gcr.io/ownersearch-176101/website-server:$TAG_NAME']
